// src/services/mockData.ts

import { Occurrence, User } from "../types";

export const MOCK_OCCURRENCES: Occurrence[] = [
  {
    id: 101,
    titule: "Incêndio em Edificação",
    type: 1,
    nome_tipo: "Incêndio",
    date: "2025-10-25T14:30:00",
    status: "Em_andamento",
    priority: "Alta",
    victims: "Nenhuma",
    details: "Fogo controlado.",
    address: "Rua da Aurora, Recife - PE",
    lat: -8.063169,
    lng: -34.871139,
  },
  {
    id: 102,
    titule: "Resgate Veicular",
    type: 2,
    nome_tipo: "Resgate",
    date: "2025-10-25T16:00:00",
    status: "Encerrada",
    priority: "Media",
    victims: "1 vítima leve",
    details: "Colisão carro x moto.",
    address: "Av. Recife, Recife - PE",
    lat: -8.047562,
    lng: -34.877001,
  },
  {
    id: 103,
    titule: "Princípio de Incêndio em Veículo",
    type: 1,
    nome_tipo: "Incêndio",
    date: "2025-10-26T09:15:00",
    status: "Em_andamento",
    priority: "Alta",
    victims: "Nenhuma",
    details: "Fumaça intensa vindo do motor.",
    address: "BR-101, Cabo de Santo Agostinho - PE",
    lat: -8.287655,
    lng: -35.032112,
  },
  {
    id: 104,
    titule: "Afogamento - Praia de Boa Viagem",
    type: 3,
    nome_tipo: "Salvamento Aquático",
    date: "2025-10-26T11:40:00",
    status: "Encerrada",
    priority: "Alta",
    victims: "1 vítima resgatada consciente",
    details: "Banho em área de risco.",
    address: "Praia de Boa Viagem, Recife - PE",
    lat: -8.121018,
    lng: -34.900331,
  },
  {
    id: 105,
    titule: "Desabamento Parcial de Estrutura",
    type: 4,
    nome_tipo: "Desabamento",
    date: "2025-10-27T08:20:00",
    status: "Em_andamento",
    priority: "Alta",
    victims: "2 vítimas presas nos escombros",
    details: "Parede de casa antiga desabou.",
    address: "Santo Amaro, Recife - PE",
    lat: -8.051234,
    lng: -34.872345,
  },
  {
    id: 106,
    titule: "Acidente com Produto Químico",
    type: 5,
    nome_tipo: "Hazmat",
    date: "2025-10-27T13:50:00",
    status: "Em_andamento",
    priority: "Alta",
    victims: "Nenhuma",
    details: "Vazamento de substância desconhecida.",
    address: "Porto de Suape, Ipojuca - PE",
    lat: -8.39175,
    lng: -34.97554,
  },
  {
    id: 107,
    titule: "Captura de Animal Peçonhento",
    type: 6,
    nome_tipo: "Auxílio ao Público",
    date: "2025-10-28T07:10:00",
    status: "Cancelada",
    priority: "Baixa",
    victims: "Nenhuma",
    details: "Moradores encontraram cobra em residência.",
    address: "Casa Amarela, Recife - PE",
    lat: -8.010245,
    lng: -34.928011,
  },
  {
    id: 108,
    titule: "Acidente com Múltiplas Vítimas",
    type: 2,
    nome_tipo: "Resgate",
    date: "2025-10-28T18:45:00",
    status: "Em_andamento",
    priority: "Alta",
    victims: "4 vítimas, sendo 1 grave",
    details: "Ônibus colidiu com caminhão.",
    address: "Av. Norte, Recife - PE",
    lat: -8.0203,
    lng: -34.9005,
  },
  {
    id: 109,
    titule: "Incêndio em Área de Mata",
    type: 1,
    nome_tipo: "Incêndio Florestal",
    date: "2025-10-29T15:30:00",
    status: "Cancelada",
    priority: "Alta",
    victims: "Nenhuma",
    details: "Área extensa com propagação rápida.",
    address: "Aldeia, Camaragibe - PE",
    lat: -8.012341,
    lng: -34.975678,
  },
  {
    id: 110,
    titule: "Árvore Caída Bloqueando Via",
    type: 6,
    nome_tipo: "Auxílio ao Público",
    date: "2025-10-30T06:30:00",
    status: "Encerrada",
    priority: "Media",
    victims: "Nenhuma",
    details: "Árvore caída após chuvas.",
    address: "Beira Rio, Recife - PE",
    lat: -8.059216,
    lng: -34.88531,
  },
];
